name: Build Osx

env:
  BuildProject: PopH264.xcodeproj
  BuildScheme: PopH264Framework

on: [push]

jobs:
  buildosx:
    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    # https://coderwall.com/p/rv2lgw/use-xcodebuild-to-build-workspace-vs-project
    # https://github.community/t5/GitHub-Actions/steps-output/td-p/30947
    - name: GetTargetBuildDir
      id: GetTargetBuildDir
      run: |
        echo "Setting target build dir"
        echo "##[set-output name=TargetBuildDir;]$(xcodebuild -workspace $BuildProject/project.xcworkspace -scheme $BuildScheme -showBuildSettings | grep TARGET_BUILD_DIR | sed -e 's/.*TARGET_BUILD_DIR = //')"

    - name: compile
      env: 
          TargetBuildDir: ${{steps.GetTargetBuildDir.outputs.TargetBuildDir}}
      run: |
          xcodebuild -workspace $BuildProject/project.xcworkspace -scheme $BuildScheme -showBuildSettings
          xcodebuild -workspace $BuildProject/project.xcworkspace -list
          xcodebuild -workspace $BuildProject/project.xcworkspace -scheme $BuildScheme
      
    - name: List artifacts
      env: 
          BuildDirectory: ${{steps.GetTargetBuildDir.outputs.TargetBuildDir}}

      run: |
        echo "Build Directory ($BuildDirectory) contents"
        ls $BuildDirectory
    
    # do not use env here: ##[error]Path does not exist d:\a\PopH264\PopH264\$Env:GITHUB_WORKSPACE\PopH264.visualstudio\Debug
    - uses: actions/upload-artifact@v1
      with:
        name: PopH264_Osx.framework
        path: ${{steps.GetTargetBuildDir.outputs.TargetBuildDir}}/PopH264_Osx.framework
    - uses: actions/upload-artifact@v1
      with:
        name: PopH264.h
        path: Source/PopH264.h
        
#PopH264.visualstudio\Debug\PopH264.dll
